services:
  wildfly:
    container_name: wildfly
    hostname: localhost
    image: quay.io/wildfly/wildfly:28.0.0.Final-jdk17
    ports:
      - "8080:8080"
    volumes:
      - ./target/lab3-1.0-SNAPSHOT.war:/opt/jboss/wildfly/standalone/deployments/lab3.war
    environment:
      DB_URL: "jdbc:postgresql://postgres:5432/postgres_db"
      DB_USER: "dbuser"
      DB_PASSWORD: "dbuser"
    depends_on:
      - postgres

  oracle:
    image: daggerok/oracle:se
    hostname: oracledb
    container_name: oracledb
    environment:
      ORACLE_SID: xe
      ORACLE_PWD: password
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - "./oracle-volume:/opt/oracle/oradata"
    restart: unless-stopped

  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbuser
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16